# Generated by Django 4.0.1 on 2022-01-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_cadastro', models.DateField()),
                ('fone_celular', models.CharField(max_length=20)),
                ('fone_whatsapp', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=200)),
                ('complemento', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=2)),
                ('obs', models.TextField(max_length=400)),
                ('cupom', models.CharField(max_length=20)),
            ],
        ),
    ]
