# Generated by Django 4.0.1 on 2022-01-10 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_lead', '0002_cupon_remove_leads_bairro_remove_leads_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='cupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='form_lead.cupon'),
        ),
    ]
