# Generated by Django 4.0.1 on 2022-01-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_lead', '0003_alter_leads_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
